### ISSUE TITLE
有时候莫名其妙的卡顿造成连接数据库异常

### ISSUE THREAD

**Issue by zygfengyuwuzu** [magicdict/MongoCola#16]
2015-03-03T13:37:47.036+0800 [conn83] AssertionException handling request, closi
ng client connection: 16810 bad query: BadValue unknown top level operator: $query

这是mongodb报的错误

**Comment by magicdict** [comment]
我也发现了日志里面的这个问题,
应该是检索数据的时候出现的,具体原因等有空了进行排查
Mongo3.0.0正式版Release了.不过CSharp的Driver做得真心烂

**Comment by weiguang3100** [comment]
cola完美支持mongo3.0了吗
