### ISSUE TITLE
MongoCola 能否提供编译完版本？

### ISSUE THREAD

**Issue by gyf19** [magicdict/MongoCola#17]
https://github.com/magicdict/MongoCola/downloads  是2012 年版本。
最新版本1.5 版本， 好像没有提供

**Comment by gyf19** [comment]
新版本可以支持 mongodb 3.0 吗？

**Comment by magicdict** [comment]
可以支持3.0
明天VS2015发布,发布后会用2015编译一个可执行版本的.
不知道你的NET版本是4.5还是可以使用4.6

**Comment by gyf19** [comment]
我是 .net 4.5 版本

**Comment by magicdict** [comment]
借用博客圆的文件系统
http://files.cnblogs.com/files/TextEditor/ReleaseVersion.zip

不好意思,由于使用了一些C#6.0的语法,NET Framework需要4.6.
今天4.6已经正式发布了.
这个版本修改的地方蛮多的,只是一个试验性质的版本,用来学习和研究没有问题.
真实生产环境的话,只是察看没有问题的.
>>新版本可以支持 mongodb 3.0 的 wiredTiger 引擎吗？
使用官方 2.0.1的驱动了,可以支持基本操作的.

**Comment by gyf19** [comment]
问题不少，简单测试了一下。
1. 创建新连接，Port 不能保存。  打开 MongoConfig.xml 文件， 把<Port>0</Port>修改<Port>27017</Port>
2. 进去后，不能创建数据库、 不能添加数据集

**Comment by magicdict** [comment]
>>问题不少，简单测试了一下。
>>1. 创建新连接，Port 不能保存。 打开 MongoConfig.xml 文件， 把0修改27017
>>2. 进去后，不能创建数据库、 不能添加数据集
最近这个版本还只是一个实验性质的版本,是有许多错误的.
至少要到8月初才能改好.Net的驱动程序修改太大了.请见谅

**Comment by magicdict** [comment]
BUG已经修复，但是还有很多BUG需要发现和修改。
本职工作现在在教育新人，所以这个项目可能暂时不能100%投入时间。
欢迎你发现更多ＢＵＧ报告给我，谢谢你。

**Comment by gyf19** [comment]
是的，  你可以支持下来就不容易了。    我有时间就会测试一下。    如何提供最新版本呢

**Comment by magicdict** [comment]
如果没有特别说明,以后我就一直将新版本放在下面这个地方
http://files.cnblogs.com/files/TextEditor/ReleaseVersion.zip
