### ISSUE TITLE
mac os 有计划开发吗？？

### ISSUE THREAD

**Issue by jacobzheng** [magicdict/MongoCola#19]
RT:

**Comment by magicdict** [comment]
暂时不会做标准的MacOs程序，代码都是C#的。
如果真的要用，可以用MONO的解决方案，现在是可以在Mac上通过MONO运行的。
国内用户比较少，尤其是非Windows平台。
实在没有精力为了Mac平台单独开发，毕竟是个人项目，没有人资助，很少有人贡献代码
