### ISSUE TITLE
程序运行问题

### ISSUE THREAD

**Issue by shipf0820** [magicdict/MongoCola#21]
1.5.3版本的ReplicaSet添加不了副本，点击add没有反应
v2.0版本的下载路径在哪里呢
中文汉化语言包在哪里？

**Comment by magicdict** [comment]
和EXE文件一起有一个Language文件夹，里面有汉化用文件的。

**Comment by magicdict** [comment]
ReplicaSet的问题，这个功能开发之后就一直没有动过，很多都是MongoDB 2.X时代的东西了，最新版本的下载地址：（Language文件夹补上了）
http://files.cnblogs.com/files/TextEditor/ReleaseVersion.zip
原来是EXE文件，不能跨平台，界面也不好看，最近正在研究网页化的问题。
准备用NET CORE重写这个工具。
感谢支持。

**Comment by shipf0820** [comment]
关于这个ReplicaSet添加不了副本，点击add没有反应问题，能否麻烦楼主给定位修复下呢？
