### ISSUE TITLE
关于这个ReplicaSet添加不了副本，点击add没有反应

### ISSUE THREAD

**Issue by shipf0820** [magicdict/MongoCola#22]
关于这个ReplicaSet添加不了副本，点击add没有反应问题，能否麻烦楼主给定位修复下呢？

**Comment by magicdict** [comment]
好的，我定位看看

**Comment by magicdict** [comment]
修复了一下，不过能不能展示副本，则没有把握，这几年没有搭建副本测试过。
前几年搭建测试过，不过是Mongo1.x的时代了。

**Comment by shipf0820** [comment]
关于副本的问题，还是没有解决，点击add没有反应问题

**Comment by magicdict** [comment]
我在Github上Release了一个版本了。
你的Add没有反应是Connection设置的地方没有反应吗？

**Comment by shipf0820** [comment]
是点击Add Host按钮副本添加不进来，见附件截图

![2016-10-18_084612](https://cloud.githubusercontent.com/assets/16833526/19460633/f1df38be-950f-11e6-92f8-cbe25cfc54b0.png)

**Comment by magicdict** [comment]
![image](https://cloud.githubusercontent.com/assets/897796/19461132/84ba2528-9514-11e6-90a3-ed47a0595ae7.png)

**Comment by magicdict** [comment]
@shipf0820 
https://github.com/magicdict/MongoCola/releases/tag/2.0
最新版Release上来了，你试试看。
