### ISSUE TITLE
启动时服务配置信息不能保存到本地，每次重启都会丢失需要重新输入服务配置信息

### ISSUE THREAD

**Issue by shipf0820** [magicdict/MongoCola#24]

**Comment by magicdict** [comment]
微信：  mywechatapp
希望能够长期合作，将这个项目做好。
很多代码都是几年前写的，最近3.4要发布了，所以想趁这个机会将代码都重新修改一遍。
感谢你认真测试，能否加个微信或者其他形式帮我做测试工作。
这个是BUG管理的地址：
https://www.bugclose.com/register.html?inviteCode=zG1SEOLl1Z

**Comment by magicdict** [comment]
严重的BUG，已经修复。
