### ISSUE TITLE
能否考虑增加MR操作的扩展功能呢

### ISSUE THREAD

**Issue by shipf0820** [magicdict/MongoCola#27]

**Comment by magicdict** [comment]
MR操作？什么叫MR操作？

**Comment by shipf0820** [comment]
mapreduce

**Comment by magicdict** [comment]
MapReduce有一个简单的实现。扩展功能有什么好的提议吗

**Comment by magicdict** [comment]
@shipf0820 
开始着手进行MR扩展功能的改造了。
界面雏形如图：
http://www.codesnippet.info/Article/Index?ArticleId=00000062#MapReduce

**Comment by magicdict** [comment]
改造完成
